apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-new
  namespace: my-ns
  labels:
    app: my-deployment
spec:
  replicas: 5
  selector:
    matchLabels:  
      app: my_app 
  template:
    metadata:
      labels:
        app: my_app
    spec:
      containers:
      - name: myapp
        image: rakshithgt96/ip 
        ports:
        - containerPort: 80
