apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp02
  name: myapp02
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp02
  template:
    metadata:
      labels:
        app: myapp02
    spec:
      containers:
      - image: nginx:latest
        name: nginx
      nodeSelector:
        high-perf-cpu: "yes"
