apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: required-hard
  name: required-hard
spec:
  replicas: 4
  selector:
    matchLabels:
      run: required-hard
  template:
    metadata:
      labels:
        run: required-hard
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: env
                operator: In
                values:
                - one

      containers:
      - image: nginx:latest
        name: required-hard
