apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp01
  name: myapp01
  namespace: my-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp01
  template:
    metadata:
      labels:
        app: myapp01
    spec:
      containers:
        - image: nginx:latest
          name: nginx
      nodeSelector:
        kubernetes.io/hostname: node1
