apiVersion: v1
kind: Pod
metadata:
  name: my-pvc-pod
spec:
  volumes: 
   - name: pvc-volume
     persistentVolumeClaim:
        claimName: my-pvc   
  containers:
    - name: my-nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pvc-volume
