apiVersion: v1
kind: Pod
metadata:
  name: startup-example
spec:
  containers:
  - name: startup
    image: k8s.gcr.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/started; sleep 3600
    startupProbe:
      exec:
        command:
        - cat
        - /tmp/started
      failureThreshold: 30
      periodSeconds: 10
