apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app1
  name: app1
  namespace: my-ns # Specify the namespace here
spec:
  replicas: 6
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - image: nginx:latest
          name: nginx
      tolerations:
        - key: "high-cpu"
          operator: "Equal"
          value: "yes"
          effect: "NoSchedule"
